### ISSUE TITLE
Socket Connect Failure: Connection Refused

### ISSUE THREAD

**Issue by PrasannaVenkadesh** [mpaperno/spampd#25]
I have setup a mail server using mail-in-a-box, which in turn installed spampd. spampd is running in the background, but all incoming emails don't get delivered to the respective inbox.

Upon inspecting the log found out the following line which causes this to fail

`spampd[1944]: WARNING!! Error in process_request eval block: /usr/sbin/spampd: socket connect failure: Connection refused`

it appears that the application is not listening on port 10026.

**Comment by mpaperno** [comment]
The error indicates that spampd could not connect to the relay destination server (presumably Dovecot but I don't know your setup). It seems most likely this is a configuration error, not due to spampd itself. We can reopen this issue if you can determine the failure is in spampd specifically.  It may help to add the `--debug` option in the spampd service startup config file.  I cannot help with mail-in-a-box setup issues.

**Comment by PrasannaVenkadesh** [comment]
@mpaperno Thanks for pointing out. I mistook port 10026 is bound by `spampd` and thus the confusion. I had modified some part of dovecot configuration from mail-in-a-box setup and missed out to enable lmtp and hence the error.
