### ISSUE TITLE
How does SpamPD differ from SpamAssassin Milter Plugin?

### ISSUE THREAD

**Issue by myfirstnameispaul** [mpaperno/spampd#28]
This obviously isn't an issue, just a question that I can't seem to figure out for myself:

What does `spampd` solve that [`spamass-milter`](https://savannah.nongnu.org/projects/spamass-milt/) does not ?

**Comment by mpaperno** [comment]
Ultimately, probably nothing.  I'm not really familiar with the milter plugin, but seems like it basically does the same thing (pass all mail through SA), just in a different way. I'm not sure it can be used on anything but Sendmail, but don't know.  It uses spamc/spamd, so that's more processes running, vs. spampd which does not (uses SA directly).  The plugin has a long open issues list, spampd does not... :-)   I would use whichever works best/simplest for your setup.
