### ISSUE TITLE
Enable --allow-tell functionality

### ISSUE THREAD

**Issue by jprjr** [mpaperno/spampd#7]
Hi there -

I'm working on setting up spampd, it's running on a separate server from everything else.

Something I like about the spamd/spamc combo, is I can use spamc -L "spam" and spamc -L  "ham" to train spamd.

As far as I can tell, spampd is meant to replace spamd, but I can't figure out how to get that functionality working.

**Comment by mpaperno** [comment]
There seem to be a couple misconceptions here...

SpamPD is not meant/designed as a replacement for `spamd`.

One does not "train" `spamd`, one adds/removes entries in the Bayes DB being used.

As such, there are multiple ways to "train" the database.  As long as the SA which SpamPD is running is configured to use the same database, the same training will apply to anything scanned via SpamPD .

To add something like "allow-tell" to SpamPD  would involve some whole new method of communicating with it while it is running... or using some S/LMTP protocol hack.  There is no way to "send commands to" the `spampd` process otherwise.  I think this issue alone makes the request out of scope for SpamPD.
